spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
logging:
  level:
    org:
      springframework:
        security: INFO
loan:
  installments: 6,9,12,24
  minInterestRate: 0.1
  maxInterestRate: 0.5
  penaltyRate: 0.001